/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a7f88db6-c87b-4e19-a6c6-e30090f7d208",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Xb7tqDZo8",
    "aws_user_pools_web_client_id": "78kfgsj8csi2t4h7mvca1i3kt1",
    "oauth": {},
    "aws_user_files_s3_bucket": "usersrekognitionaps3163244-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "predictions": {
        "identify": {
            "identifyEntities": {
                "proxy": false,
                "region": "us-east-1",
                "celebrityDetectionEnabled": true
            }
        }
    }
};


export default awsmobile;
